#!/usr/bin/env bash
#using while loop
while IFS=':' read -r username _ userid groupid _ homedir shell; do
  info=$(grep -w "$userid" /etc/passwd)
  passcode=$(echo "$info" | cut -d':' -f2)
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $info"
done < "/etc/passwd"
