#!/usr/bin/env bash
#using while loop and ifs
IFS=":"
while read -r username password userid groupid userdesc homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userid $userdesc"
done < /etc/passwd
