#!/usr/bin/env bash
#bash process
ps_output=$(ps -ef)

# Filter the lines containing the word "bash" and include PID
bash_lines=$(echo "$ps_output" | grep "[b]ash")

# Print the lines containing "bash" with PID
echo "$bash_lines"

# Extract the PID from the filtered lines
bash_pid=$(echo "$bash_lines" | awk '{print $2}')

# Print the extracted PID
echo "Here we can see that my Bash PID is $bash_pid."
