#!/usr/bin/env bash
#bash script
process_ids=$(find /proc -maxdepth 1 -type d -name '[0-9]*' -exec basename {} \; 2>/dev/null)
process_names=()

# Iterate over the process IDs
for pid in $process_ids; do
    # Check if the process name contains the word "bash"
    if grep -q "bash" "/proc/$pid/comm" 2>/dev/null; then
        # Read the process name from the /proc/[pid]/comm file
        name=$(cat "/proc/$pid/comm" 2>/dev/null)
        process_names+=("$name $pid")
    fi
done

# Display the process names and PIDs
for name_pid in "${process_names[@]}"; do
    echo "$name_pid"
done
